Models/ErrorViewModel.cs
using System;

namespace InAndOut.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Expense.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InAndOut.Models
{
    public class Expense
    {
        [Key]
        public int Id { get; set; }

        [DisplayName("Expense Name")]
        [Required]
        public string Name { get; set; }

        [Required]
        [Range(0.1, double.MaxValue, ErrorMessage = "Amount must be greater than 0.")]
        [Column(TypeName = "decimal(18,2)")]
        public decimal Amount { get; set; }
    }
}

Models/Item.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace InAndOut.Models
{
    public class Item
    {
        [Key]
        public int Id { get; set; }

        [MaxLength(50)]
        public string Borrower { get; set; }

        [MaxLength(50)]
        public string Lender { get; set; }

        [Required]
        [MaxLength(50)]
        [DisplayName("Item Name")]
        public string Name { get; set; }
    }
}

Controllers/AppointmentController.cs
using Microsoft.AspNetCore.Mvc;

namespace InAndOut.Controllers
{
    public class AppointmentController : Controller
    {
        public IActionResult Index()
        {
            return View();
            //string todaysDate = DateTime.Now.ToShortDateString();
            //return Ok(todaysDate);
        }

        public IActionResult Details(int id)
        {
            return Ok($"You have entered id = {id}");
        }
    }
}

Controllers/ExpenseController.cs
using System.Collections.Generic;
using InAndOut.Data;
using InAndOut.Models;
using Microsoft.AspNetCore.Mvc;

namespace InAndOut.Controllers
{
    public class ExpenseController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ExpenseController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Expense> objList = _db.Expenses;
            return View(objList);
        }

        // Get
        public IActionResult Create()
        {
            return View();
        }

        // Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Expense obj)
        {
            // validation
            if (ModelState.IsValid)
            {
                _db.Expenses.Add(obj);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View();
        }

        // Get
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.Expenses.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        // Post Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.Expenses.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            else
            {
                _db.Expenses.Remove(obj);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }
        }

        // Get
        public IActionResult Update(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.Expenses.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        // Post Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Expense obj)
        {
            // validation
            if (ModelState.IsValid)
            {
                _db.Expenses.Update(obj);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using InAndOut.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace InAndOut.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ItemController.cs
using System.Collections.Generic;
using InAndOut.Data;
using InAndOut.Models;
using Microsoft.AspNetCore.Mvc;

namespace InAndOut.Controllers
{
    public class ItemController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ItemController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Item> objList = _db.Items;
            return View(objList);
        }

        // Get
        public IActionResult Create()
        {
            return View();
        }

        // Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Item obj)
        {
            _db.Items.Add(obj);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

Controllers/ReturnTypeController.cs
using Microsoft.AspNetCore.Mvc;

namespace InAndOut.Controllers
{
    public class ReturnTypeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        #region :: Status Code Result ::
        public IActionResult OkResult()
        {
            return Ok();
        }
        #endregion


    }
}

Views/Appointment/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

Views/Expense/Create.cshtml
@model InAndOut.Models.Expense

@{
    ViewData["Title"] = "Create";
}

<h1>Create new Expense</h1>

<form method="post" asp-action="Create">

    <div class="border p-3">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Add Item</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Amount"></label>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <input asp-for="Amount" class="form-control" />
                        <span asp-validation-for="Amount" class="text-danger"></span>
                    </div>
                </div>

            </div>
        </div>

        <div class="form-group row text-right p-3">
            <button type="submit" class="btn btn-primary">Create</button>
            &nbsp;
            <button class="btn btn-warning cancel" asp-action="Index" disableValidation="true">Back</button>
        </div>

    </div>

</form>

@section Scripts {
    @{
        // local validation
        // by adding below partial page, it will validate using javascript and will not hit database for validation.
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Expense/Delete.cshtml
@model InAndOut.Models.Expense

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete Expense</h1>

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Delete Expense</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Amount"></label>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <input disabled asp-for="Name" class="form-control" />
                    </div>
                    <div class="col-4">
                        <input disabled asp-for="Amount" class="form-control" />
                    </div>
                </div>

            </div>
        </div>

        <div class="form-group row text-right p-3">
            <button type="submit" class="btn btn-danger">Delete</button>
            &nbsp;
            <button class="btn btn-success cancel" asp-action="Index" disableValidation="true">Back</button>
        </div>

    </div>

</form>

Views/Expense/Index.cshtml
@model IEnumerable<InAndOut.Models.Expense>

@{
    ViewData["Title"] = "Index";
}

<h1>Index - Expense</h1>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Expenses List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Expense" asp-action="Create" class="btn btn-primary">Create new Expense</a>
        </div>
    </div>
    <br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th><label asp-for="First().Name"></label></th>
                    <th><label asp-for="First().Amount"></label></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td width="35%">@item.Name</td>
                        <td width="35%">@item.Amount</td>
                        <td width="30%">
                            <div class="w-100 btn-group" role="group">
                                <a asp-controller="Expense" asp-action="Update" asp-route-Id="@item.Id" class="btn btn-warning mx-1">Update</a>
                                <a asp-controller="Expense" asp-action="Delete" asp-route-Id="@item.Id" class="btn btn-danger mx-1">Delete</a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No expense created yet</p>
    }

</div>

Views/Expense/Update.cshtml
@model InAndOut.Models.Expense

@{
    ViewData["Title"] = "Update";
}

<h1>Update expense</h1>

<form method="post" asp-action="Update">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Update Item</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Amount"></label>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <input asp-for="Amount" class="form-control" />
                        <span asp-validation-for="Amount" class="text-danger"></span>
                    </div>
                </div>

            </div>
        </div>

        <div class="form-group row text-right p-3">
            <button type="submit" class="btn btn-primary">Update</button>
            &nbsp;
            <button class="btn btn-success cancel" asp-action="Index" disableValidation="true">Back</button>
        </div>

    </div>

</form>

@section Scripts {
    @{
        // local validation
        // by adding below partial page, it will validate using javascript and will not hit database for validation.
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome Sharizan</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Item/Create.cshtml
@model InAndOut.Models.Item

@{
    ViewData["Title"] = "Create";
}

<h1>Create new Item</h1>


<form method="post" asp-action="Create">

    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Add Item</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Borrower"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Lender"></label>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <input asp-for="Name" class="form-control" />
                    </div>
                    <div class="col-4">
                        <input asp-for="Borrower" class="form-control" />
                    </div>
                    <div class="col-4">
                        <input asp-for="Lender" class="form-control" />
                    </div>
                </div>

            </div>
        </div>

        <div class="form-group row text-right p-3">
            <button type="submit" class="btn btn-primary">Create</button>
            &nbsp;
            <button class="btn btn-warning" asp-action="Index">Back</button>
        </div>

    </div>

</form>

Views/Item/Index.cshtml
@model IEnumerable<InAndOut.Models.Item>

@{
    ViewData["Title"] = "Index";
}

<h1>Index - Items</h1>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Borrowed Items List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Item" asp-action="Create" class="btn btn-primary">Create new Item</a>
        </div>
    </div>
    <br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Item Name</th>
                    <th>Borrower</th>
                    <th>Lender</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td width="30%">@item.Name</td>
                        <td width="30%">@item.Borrower</td>
                        <td width="30%">@item.Lender</td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No items created yet</p>
    }

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InAndOut</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InAndOut</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Index">My Borrowed Items</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Expense" asp-action="Index">My Expenses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - InAndOut - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>